// Constants file

// PETSCII
.const PETSCII_WHITE = $05
.const PETSCII_RED = $1C
.const PETSCII_GREEN = $1E
.const PETSCII_BLUE = $1F
.const PETSCII_ORANGE = $81
.const PETSCII_BLACK = $90
.const PETSCII_BROWN = $95
.const PETSCII_PURPLE = $9C


.const PETSCII_CUR_DOWN = $11
.const PETSCII_CUR_RIGHT = $1D
.const PETSCII_CUR_UP = $91
.const PETSCII_CUR_LEFT = $9D

.const PETSCII_REV_ON = $12
.const PETSCII_REV_OFF = $92
.const PETSCII_HOME = $13
.const PETSCII_CLEAR = $93

.const PETSCII_DELETE = $14